#!/bin/sh

# Run programs embeded into MarkDown documents

PROGRAM=${1?Expected program filename}

typeset line
typeset -i onblock=0

echo 1>&2 ">>> Running: $PROGRAM"

while read -r line; do
    if [[ $line == '```'* ]]; then
        if (( onblock )); then
            onblock=0
        else
            onblock=1
        fi
        echo
    else
        if (( onblock )); then
            echo "$line"
        else
            echo
        fi
    fi
done < "$PROGRAM" | case "$PROGRAM" in
    *.sh.md) sh - ;;
    *.py.md) python - ;;
    *) cat - ;;
esac


exit

# vim:ai:et:sw=4:ts=4:syntax=sh
